export const LIST_PATH = '/dashboard'
export const WALLET_PATH = '/wallet'
export const REFERRAL_INCOME_PATH = '/referral-income'
export const USERS_PATH = '/admin'
export const ACCOUNT_PATH = '/account'
export const LOGIN_PATH = '/login'
export const SIGNUP_PATH = '/signup'
